#!/usr/bin/env bash
# Bump a plugin's version across all four manifests that must agree.
#
# A plugin's version lives in four places — the portable manifest, the strict Claude manifest,
# and one entry in each of the two marketplace manifests — and validate-manifests.sh fails if
# they disagree. Doing that by hand is four edits and an easy way to ship a half-bumped plugin,
# so this is the one supported way to move a version.
#
# Consumers cache plugins by version, so a content change that leaves the version untouched
# never reaches them; check-plugin-version-bump.sh is the gate that catches it, and this is the
# fix that gate points at.
#
# Usage:
#   ./scripts/bump-plugin-version.sh <plugin> [patch|minor|major]   # bump one plugin
#   ./scripts/bump-plugin-version.sh --changed-since <ref> [level]  # bump every plugin whose
#                                                                   # content changed since <ref>
#
# The --changed-since mode is what the automated skill sync uses: it bumps exactly the plugins
# whose shipped content moved, so the daily update PR satisfies the gate without a human edit.
set -euo pipefail

CLAUDE_MANIFEST=".claude-plugin/marketplace.json"
COPILOT_MANIFEST=".github/plugin/marketplace.json"

# shellcheck source=scripts/plugin-version.lib.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/plugin-version.lib.sh"

# All generated bytes stay outside the repository until the whole plan is valid.
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
: > "$work/changes"
for manifest in "$CLAUDE_MANIFEST" "$COPILOT_MANIFEST"; do
  jq -e 'type == "object" and (.plugins | type == "array")' "$manifest" >/dev/null || exit 1
  cp "$manifest" "$work/$(basename "$(dirname "$manifest")").json"
done

plan_one() {
  local name="$1" level="$2" dir="plugins/$1" current new manifest staged entry
  [[ "$name" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]] || { echo '::error::Invalid plugin identity.' >&2; return 1; }
  current=$(jq -er '.version | select(type == "string")' "$dir/.claude-plugin/plugin.json") || return 1
  plugin_version_valid "$current" || { echo '::error::Invalid cache version.' >&2; return 1; }
  for manifest in "$dir/plugin.json" "$dir/.claude-plugin/plugin.json"; do
    jq -e --arg n "$name" --arg v "$current" '.name == $n and .version == $v' "$manifest" >/dev/null || {
      echo "::error::$manifest: plugin identity or version parity is invalid; no manifests were changed." >&2
      return 1
    }
  done
  for manifest in "$CLAUDE_MANIFEST" "$COPILOT_MANIFEST"; do
    staged="$work/$(basename "$(dirname "$manifest")").json"
    jq -e --arg n "$name" --arg v "$current" '
      [.plugins[] | select(.name == $n)] | length == 1 and
      (.[0] | .version == $v and .source == ("./plugins/" + $n))' "$staged" >/dev/null || {
      echo "::error::$manifest: expected one matching plugin at the same version; no manifests were changed." >&2
      return 1
    }
  done
  # Changed-since must validate even a plugin already bumped on the branch.
  if [ "$level" = keep ]; then return 0; fi
  new=$(plugin_version_next "$current" "$level") || return 1
  for manifest in "$dir/plugin.json" "$dir/.claude-plugin/plugin.json"; do
    entry="$work/plugin-$(wc -c < "$work/changes" | tr -d ' ')"
    jq --arg v "$new" '.version = $v' "$manifest" > "$entry" || return 1
    printf '%s\0%s\0' "$manifest" "$entry" >> "$work/changes"
  done
  for manifest in "$CLAUDE_MANIFEST" "$COPILOT_MANIFEST"; do
    staged="$work/$(basename "$(dirname "$manifest")").json"
    jq --arg n "$name" --arg v "$new" '.plugins |= map(if .name == $n then .version = $v else . end)' "$staged" > "$work/next" || return 1
    mv "$work/next" "$staged"
  done
  echo "✓ $name $current → $new"
}

# Select a single plugin or finish every changed-plugin observation before writing versions.
main() {
  local level plugins

  if [ "${1:-}" = "--changed-since" ]; then
    local base="${2:?--changed-since needs a base ref}"
    level="${3:-patch}"
    local base_sha
    if ! base_sha=$(git merge-base "$base" HEAD 2>/dev/null); then
      echo "::error::Cannot resolve a merge base for '$base'...HEAD." >&2
      exit 1
    fi
    # Complete all observations before bump_one writes any manifest. A failed
    # producer may have emitted a plausible prefix; that prefix is not a census.
    local plugin_dirs changed
    if ! plugin_dirs=$(git ls-tree -d --name-only HEAD plugins/); then
      echo "::error::Cannot enumerate plugins at HEAD; no versions were changed." >&2
      return 1
    fi
    plugins=""
    while IFS= read -r plugin_dir; do
      [ -n "$plugin_dir" ] || continue
      if ! changed=$(git diff --name-only "$base_sha" HEAD -- "$plugin_dir/"); then
        echo "::error::Cannot inspect changed content for '$plugin_dir'; no versions were changed." >&2
        return 1
      fi
      [ -n "$changed" ] || continue

      # The goal is "this plugin's version moved", not "add one every run". If a previous
      # pass (or a human) already bumped it relative to the base, re-running must be a
      # no-op — otherwise a re-run of the sync workflow inflates the version each time.
      local manifest_rel=".claude-plugin/plugin.json"
      local base_v head_v
      base_v=$(git show "$base_sha:$plugin_dir/$manifest_rel" 2>/dev/null | jq -r '.version // empty')
      head_v=$(jq -r '.version // empty' "$plugin_dir/$manifest_rel" 2>/dev/null)
      if [ -n "$base_v" ] && [ "$base_v" != "$head_v" ]; then
        plugin_version_increases "$base_v" "$head_v" || { echo '::error::Cache versions must increase.' >&2; return 1; }
        plan_one "${plugin_dir#plugins/}" keep || return 1
        echo "✓ ${plugin_dir#plugins/} already moved $base_v → $head_v — leaving it"
        continue
      fi
      plugins="$plugins ${plugin_dir#plugins/}"
    done <<< "$plugin_dirs"
    if [ -z "${plugins// /}" ]; then
      echo "✓ No plugin content changed since $base — nothing to bump"
      return 0
    fi
  else
    plugins="${1:?usage: bump-plugin-version.sh <plugin> [patch|minor|major]}"
    level="${2:-patch}"
  fi

  local p
  for p in $plugins; do
    plan_one "$p" "$level"
  done
  # Only complete plans are installed; a bad later input cannot half-bump a plugin.
  local destination staged
  while IFS= read -r -d '' destination && IFS= read -r -d '' staged; do
    cat "$staged" > "$destination"
  done < "$work/changes"
  for destination in "$CLAUDE_MANIFEST" "$COPILOT_MANIFEST"; do
    staged="$work/$(basename "$(dirname "$destination")").json"
    cat "$staged" > "$destination"
  done
}

main "$@"
