include "marketplace-release";

def publication_notes($release):
  ["> 🤖 Generated by the Agentic Engineer", "# Marketplace \(.version)",
   "Source commit: `\(.sourceCommit)`", "Release commit: `\($release)`",
   "Baseline: \(if .baseline == null then "initial snapshot" else "`"+.baseline.tag+"` at `"+.baseline.commit+"`" end)",
   "## Changes", (.commits[] | "- \(.subject | markdown_text) (`\(.sha)`)"),
   "## Plugin inventory", (.plugins[] | "- \(.name | markdown_text): \(.version | markdown_text)"),
   "Per-plugin versions and runtime cache identities remain independent of the marketplace version."
  ] | join("\n\n") + "\n";

def publication_snapshot($phase;$repo;$branch;$tag;$release;$id;$notes):
  type=="object" and (.errors==null or .errors==[]) and
  (.data.repository | type=="object" and .nameWithOwner==$repo and .isArchived==false and
    (.viewerPermission|.=="ADMIN" or .=="MAINTAIN" or .=="WRITE") and
    .defaultBranchRef.name==$branch and .defaultBranchRef.target.__typename=="Commit" and
    .defaultBranchRef.target.oid==$release and has("ref") and has("release") and
    (if $phase=="absent" then .ref==null else
       .ref.prefix=="refs/tags/" and .ref.name==$tag and .ref.target.__typename=="Commit" and .ref.target.oid==$release
     end) and
    (if $phase!="published" then .release==null else
       (.release | type=="object" and .databaseId==$id and .tagName==$tag and .isDraft==false and
         .isPrerelease==false and .name==$tag and .description==$notes and
         (.publishedAt|type=="string" and length>0) and .tagCommit.oid==$release and
         .url==("https://github.com/"+$repo+"/releases/tag/"+$tag))
     end));
